2019-12-10 11:12:33,811 INFO: Flaskapp startup [in C:\Users\sguthart\Radius Global Market Research\AA - Documents\Python\analytics\app\__init__.py:50]
2019-12-10 11:12:46,855 INFO: Flaskapp startup [in C:\Users\sguthart\Radius Global Market Research\AA - Documents\Python\analytics\app\__init__.py:50]
2019-12-10 11:45:40,559 INFO: Flaskapp startup [in C:\Users\sguthart\Radius Global Market Research\AA - Documents\Python\analytics\app\__init__.py:53]
2019-12-10 11:46:51,257 ERROR: Exception on /augmd/ [POST] [in c:\users\sguthart\.ve\analytics\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\sguthart\.ve\analytics\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\sguthart\.ve\analytics\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\sguthart\.ve\analytics\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\sguthart\.ve\analytics\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\sguthart\.ve\analytics\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\sguthart\.ve\analytics\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\sguthart\Radius Global Market Research\AA - Documents\Python\analytics\app\augmd\routes.py", line 18, in index
    md = pd.read_excel(save_excel(form.max_diff_data.data, 'md'))
  File "C:\Users\sguthart\Radius Global Market Research\AA - Documents\Python\analytics\app\augmd\routes.py", line 50, in save_excel
    data.save(filename)
  File "c:\users\sguthart\.ve\analytics\lib\site-packages\werkzeug\datastructures.py", line 2800, in save
    dst = open(dst, "wb")
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\sguthart\\Radius Global Market Research\\AA - Documents\\Python\\analytics\\instance\\files\\md.xlsx'
2019-12-10 11:47:29,569 ERROR: Exception on /augmd/ [POST] [in c:\users\sguthart\.ve\analytics\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\sguthart\.ve\analytics\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\sguthart\.ve\analytics\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\sguthart\.ve\analytics\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\sguthart\.ve\analytics\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\sguthart\.ve\analytics\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\sguthart\.ve\analytics\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\sguthart\Radius Global Market Research\AA - Documents\Python\analytics\app\augmd\routes.py", line 18, in index
    md = pd.read_excel(save_excel(form.max_diff_data.data, 'md'))
  File "C:\Users\sguthart\Radius Global Market Research\AA - Documents\Python\analytics\app\augmd\routes.py", line 50, in save_excel
    data.save(filename)
  File "c:\users\sguthart\.ve\analytics\lib\site-packages\werkzeug\datastructures.py", line 2800, in save
    dst = open(dst, "wb")
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\sguthart\\Radius Global Market Research\\AA - Documents\\Python\\analytics\\instance\\files\\md.xlsx'
2019-12-10 11:47:52,198 ERROR: Exception on /augmd/ [POST] [in c:\users\sguthart\.ve\analytics\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\sguthart\.ve\analytics\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\sguthart\.ve\analytics\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\sguthart\.ve\analytics\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\sguthart\.ve\analytics\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\sguthart\.ve\analytics\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\sguthart\.ve\analytics\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\sguthart\Radius Global Market Research\AA - Documents\Python\analytics\app\augmd\routes.py", line 18, in index
    md = pd.read_excel(save_excel(form.max_diff_data.data, 'md'))
  File "C:\Users\sguthart\Radius Global Market Research\AA - Documents\Python\analytics\app\augmd\routes.py", line 50, in save_excel
    data.save(filename)
  File "c:\users\sguthart\.ve\analytics\lib\site-packages\werkzeug\datastructures.py", line 2800, in save
    dst = open(dst, "wb")
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\sguthart\\Radius Global Market Research\\AA - Documents\\Python\\analytics\\instance\\files\\md.xlsx'
2019-12-10 11:49:48,622 ERROR: Exception on /augmd/ [POST] [in c:\users\sguthart\.ve\analytics\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\sguthart\.ve\analytics\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\sguthart\.ve\analytics\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\sguthart\.ve\analytics\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\sguthart\.ve\analytics\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\sguthart\.ve\analytics\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\sguthart\.ve\analytics\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\sguthart\Radius Global Market Research\AA - Documents\Python\analytics\app\augmd\routes.py", line 18, in index
    md = pd.read_excel(save_excel(form.max_diff_data.data, 'md'))
  File "c:\users\sguthart\.ve\analytics\lib\site-packages\pandas\util\_decorators.py", line 208, in wrapper
    return func(*args, **kwargs)
  File "c:\users\sguthart\.ve\analytics\lib\site-packages\pandas\io\excel\_base.py", line 310, in read_excel
    io = ExcelFile(io, engine=engine)
  File "c:\users\sguthart\.ve\analytics\lib\site-packages\pandas\io\excel\_base.py", line 819, in __init__
    self._reader = self._engines[engine](self._io)
  File "c:\users\sguthart\.ve\analytics\lib\site-packages\pandas\io\excel\_xlrd.py", line 20, in __init__
    import_optional_dependency("xlrd", extra=err_msg)
  File "c:\users\sguthart\.ve\analytics\lib\site-packages\pandas\compat\_optional.py", line 93, in import_optional_dependency
    raise ImportError(message.format(name=name, extra=extra)) from None
ImportError: Missing optional dependency 'xlrd'. Install xlrd >= 1.0.0 for Excel support Use pip or conda to install xlrd.
